### ISSUE TITLE
Problem with jobs-indeed package

### ISSUE THREAD

**Issue by sakanaproductions** [jobapis/jobs-common#17] opened 2015-11-05 19:04 UTC
I created a laravel package to encorporate the the indeed package, but am running into the following error: OutOfRangeException in AbstractProvider.php line 241... if you're interested in looking at the package, it's sakanaproductions/jbIndeed.

**Comment by stevenmaguire** [comment] 2015-11-05 19:10
Can you share a bit more information about how this exception is raised? I am assuming it was raised while you were using the package within a Laravel application. Can you share some more context around what that code was doing?

**Comment by sakanaproductions** [comment] 2015-11-05 19:14
I am trying to get jobs.  The code below is called within a jobs controller search function.  

```
$client = new jbIndeed();

        $jobs = $client->setKeyword($what)
            ->setLocation($where)
            ->includeLatLong(true)
            ->setUserIp($_SERVER['REMOTE_ADDR'])
            ->setUserAgent($_SERVER['HTTP_USER_AGENT'])
            ->getJobs();
```

**Comment by karllhughes** [comment] 2015-11-05 19:20
Might wanna try removing the setUserIp and setUserAgent method calls. Those
get set automatically anyway.

**Comment by stevenmaguire** [comment] 2015-11-05 19:24
The OutOfRangeException referenced in this issue is a side effect of the package attempting to access a specific index in the response payload that does not exist. The exception is designed to include a message with the offending index. Can you catch the exception and report back here with the output of `$exception->getMessage()`?

``` php
$client = new jbIndeed();

try {
    $jobs = $client->setKeyword($what)
        ->setLocation($where)
        ->includeLatLong(true)
        ->setUserIp($_SERVER['REMOTE_ADDR'])
        ->setUserAgent($_SERVER['HTTP_USER_AGENT'])
        ->getJobs();
} catch (\Exception $exception) {
    echo $exception->getMessage();
}
```

**Comment by sakanaproductions** [comment] 2015-11-05 19:30
the offending index is: Attempt to access missing variable: results... I did a dump inside of the error'd function and the result set is 0

On a side note, I tried removing setUserIp / setUserAgent, and it still came back with out of range error.

**Comment by stevenmaguire** [comment] 2015-11-05 19:36
That is bizarre. The results node is the correct node for the Indeed response. Unfortunately, we may need to do a bit more debugging from your environment. 

Can you open the AbstractProvider file in your vendor directories? Once open, around line 127 you should see a `$body` variable being set. Immediately following this line can you temporarily include a `dd($body)` and share the results here?

**Comment by sakanaproductions** [comment] 2015-11-05 19:38
ahh, that was the trick, my publisher number was invalid... hmm, guess i'll have to do some digging on my end as to why it is:

```
<?xml version="1.0" encoding="UTF-8" ?>\n
<response>\n
    <query></query>\n
    <location></location>\n
    <dupefilter>false</dupefilter>\n
    <highlight>false</highlight>\n
    <totalresults>0</totalresults>\n
    <start>0</start>\n
    <end>0</end>\n
    <results/>\n
    <error>You attempted an API search with invalid publisher number: 0</error>\n
</response>
```

Might be nice to have a validation for that

**Comment by stevenmaguire** [comment] 2015-11-05 19:43
Ah, well that solves the cause of your symptom. I am still not satisfied with the way the package handled that. Could you go one more step for me please?

Just before the line where the `$body` variable is set, the `$response` variable is also set. Could you place a `dd($response->getStatusCode())` immediately following the declaration of the `$response` variable and paste the results here?

**Comment by sakanaproductions** [comment] 2015-11-05 19:49
```
array:1 [▼
  "publisher" => 0
]
```

**Comment by sakanaproductions** [comment] 2015-11-05 19:53
what I'm now finding interesting is I'm calling my package client jbIndeed, but when I put a `dd(anything)` in the construct function, it doesn't get executed.

also, doing further testing, if I hardcode everything like so:

```
$client = new jbIndeed([
            'publisher' => '2391038017741504',
            'v' => 2,
            'highlight' => 0
        ]);
```

It returns back the correct array.  However if I just `config('jbIndeed.publisher')` it returns back nothing, except if i `dd(config('jbIndeed.publisher')` it outputs the correct publisher id

**Comment by stevenmaguire** [comment] 2015-11-05 20:03
Ok. It seems like there is a bit more debugging needed on your end. I'm going to open a separate issue to explore graceful handling of unexpected responses for downstream packages. In the mean time, I will close this issue. Good luck with your debugging! Karl is a regular user of these packages and he has not run into many issues, so I am confident there is something within your power to get this working properly. Please feel free to create new issues if anything significant comes up.

**Comment by sakanaproductions** [comment] 2015-11-05 20:04
okay, WOAH! This was totally my fault in my package.  I had set variables wrong.  This has been updated and fixed... thanks for the help guys

**Closed as completed by stevenmaguire** 2015-11-05 20:03 UTC

**Comment by stevenmaguire** [comment] 2015-11-05 20:12
Happy to help!
